// <auto-generated />

#region Using directives

using System;
using System.Reflection;
using System.Runtime.InteropServices;

#endregion

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyCompany("Chad Weimer")]
[assembly: AssemblyProduct("MwM")]
[assembly: AssemblyCopyright("Copyright (c) Chad Weimer")]
[assembly: AssemblyTrademark("")]
