// <auto-generated />

#region Using directives

using System;
using System.Reflection;
using System.Runtime.InteropServices;

#endregion

// The assembly version has following format :
//
// Major.Minor.Build.Revision
//
// You can specify all the values or you can use the default the Revision and 
// Build Numbers by using the '*' as shown below:
[assembly: AssemblyVersion("0.2.0.*")]
